/**
 * Pokemon GO Web Edition - Master Pokemon & Move Dataset
 */
const POKEMON_DATA = [
  { id: 1, name: "Bulbasaur", type1: "Grass", type2: "Poison", baseCP: 350, maxCP: 1115, baseHp: 65, evolvesTo: 2, candyNeeded: 25, catchRate: 0.7, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png", fastMove: "Vine Whip", chargeMove: "Seed Bomb" },
  { id: 2, name: "Ivysaur", type1: "Grass", type2: "Poison", baseCP: 850, maxCP: 1699, baseHp: 95, evolvesTo: 3, candyNeeded: 100, catchRate: 0.45, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png", fastMove: "Razor Leaf", chargeMove: "Solar Beam" },
  { id: 3, name: "Venusaur", type1: "Grass", type2: "Poison", baseCP: 1650, maxCP: 2720, baseHp: 150, evolvesTo: null, candyNeeded: 0, catchRate: 0.2, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png", fastMove: "Vine Whip", chargeMove: "Frenzy Plant" },
  { id: 4, name: "Charmander", type1: "Fire", type2: null, baseCP: 380, maxCP: 980, baseHp: 58, evolvesTo: 5, candyNeeded: 25, catchRate: 0.7, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png", fastMove: "Ember", chargeMove: "Flame Charge" },
  { id: 5, name: "Charmeleon", type1: "Fire", type2: null, baseCP: 900, maxCP: 1653, baseHp: 90, evolvesTo: 6, candyNeeded: 100, catchRate: 0.45, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png", fastMove: "Fire Fang", chargeMove: "Flamethrower" },
  { id: 6, name: "Charizard", type1: "Fire", type2: "Flying", baseCP: 1800, maxCP: 2889, baseHp: 145, evolvesTo: null, candyNeeded: 0, catchRate: 0.2, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png", fastMove: "Fire Spin", chargeMove: "Blast Burn" },
  { id: 7, name: "Squirtle", type1: "Water", type2: null, baseCP: 340, maxCP: 946, baseHp: 62, evolvesTo: 8, candyNeeded: 25, catchRate: 0.7, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png", fastMove: "Water Gun", chargeMove: "Aqua Tail" },
  { id: 8, name: "Wartortle", type1: "Water", type2: null, baseCP: 820, maxCP: 1488, baseHp: 98, evolvesTo: 9, candyNeeded: 100, catchRate: 0.45, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png", fastMove: "Water Gun", chargeMove: "Hydro Pump" },
  { id: 9, name: "Blastoise", type1: "Water", type2: null, baseCP: 1700, maxCP: 2466, baseHp: 155, evolvesTo: null, candyNeeded: 0, catchRate: 0.2, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png", fastMove: "Water Gun", chargeMove: "Hydro Cannon" },
  { id: 25, name: "Pikachu", type1: "Electric", type2: null, baseCP: 420, maxCP: 938, baseHp: 55, evolvesTo: 26, candyNeeded: 50, catchRate: 0.75, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png", fastMove: "Thunder Shock", chargeMove: "Thunderbolt" },
  { id: 26, name: "Raichu", type1: "Electric", type2: null, baseCP: 1200, maxCP: 2182, baseHp: 110, evolvesTo: null, candyNeeded: 0, catchRate: 0.35, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png", fastMove: "Volt Switch", chargeMove: "Wild Charge" },
  { id: 92, name: "Gastly", type1: "Ghost", type2: "Poison", baseCP: 480, maxCP: 1229, baseHp: 48, evolvesTo: 93, candyNeeded: 25, catchRate: 0.65, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png", fastMove: "Lick", chargeMove: "Shadow Ball" },
  { id: 93, name: "Haunter", type1: "Ghost", type2: "Poison", baseCP: 1050, maxCP: 1963, baseHp: 85, evolvesTo: 94, candyNeeded: 100, catchRate: 0.4, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png", fastMove: "Shadow Claw", chargeMove: "Shadow Punch" },
  { id: 94, name: "Gengar", type1: "Ghost", type2: "Poison", baseCP: 1950, maxCP: 2878, baseHp: 130, evolvesTo: null, candyNeeded: 0, catchRate: 0.18, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png", fastMove: "Shadow Claw", chargeMove: "Shadow Ball" },
  { id: 133, name: "Eevee", type1: "Normal", type2: null, baseCP: 450, maxCP: 1071, baseHp: 75, evolvesTo: 134, candyNeeded: 25, catchRate: 0.7, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png", fastMove: "Quick Attack", chargeMove: "Swift" },
  { id: 134, name: "Vaporeon", type1: "Water", type2: null, baseCP: 1650, maxCP: 3114, baseHp: 215, evolvesTo: null, candyNeeded: 0, catchRate: 0.25, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png", fastMove: "Water Gun", chargeMove: "Hydro Pump" },
  { id: 135, name: "Jolteon", type1: "Electric", type2: null, baseCP: 1550, maxCP: 2888, baseHp: 120, evolvesTo: null, candyNeeded: 0, catchRate: 0.25, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png", fastMove: "Thunder Shock", chargeMove: "Thunderbolt" },
  { id: 136, name: "Flareon", type1: "Fire", type2: null, baseCP: 1600, maxCP: 3029, baseHp: 125, evolvesTo: null, candyNeeded: 0, catchRate: 0.25, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png", fastMove: "Fire Spin", chargeMove: "Overheat" },
  { id: 143, name: "Snorlax", type1: "Normal", type2: null, baseCP: 1850, maxCP: 3225, baseHp: 260, evolvesTo: null, candyNeeded: 0, catchRate: 0.15, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png", fastMove: "Lick", chargeMove: "Body Slam" },
  { id: 149, name: "Dragonite", type1: "Dragon", type2: "Flying", baseCP: 2100, maxCP: 3793, baseHp: 165, evolvesTo: null, candyNeeded: 0, catchRate: 0.12, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png", fastMove: "Dragon Breath", chargeMove: "Dragon Claw" },
  { id: 150, name: "Mewtwo", type1: "Psychic", type2: null, baseCP: 2750, maxCP: 4178, baseHp: 180, evolvesTo: null, candyNeeded: 0, catchRate: 0.08, isLegendary: true, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png", fastMove: "Psycho Cut", chargeMove: "Psystrike" },
  { id: 248, name: "Tyranitar", type1: "Rock", type2: "Dark", baseCP: 2200, maxCP: 3834, baseHp: 180, evolvesTo: null, candyNeeded: 0, catchRate: 0.12, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png", fastMove: "Smack Down", chargeMove: "Stone Edge" },
  { id: 384, name: "Rayquaza", type1: "Dragon", type2: "Flying", baseCP: 2600, maxCP: 3835, baseHp: 170, evolvesTo: null, candyNeeded: 0, catchRate: 0.08, isLegendary: true, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png", fastMove: "Dragon Tail", chargeMove: "Outrage" },
  { id: 448, name: "Lucario", type1: "Fighting", type2: "Steel", baseCP: 1750, maxCP: 2703, baseHp: 135, evolvesTo: null, candyNeeded: 0, catchRate: 0.2, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png", fastMove: "Counter", chargeMove: "Aura Sphere" },
  { id: 445, name: "Garchomp", type1: "Dragon", type2: "Ground", baseCP: 2250, maxCP: 3962, baseHp: 185, evolvesTo: null, candyNeeded: 0, catchRate: 0.12, sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png", miniSprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/445.png", fastMove: "Mud Shot", chargeMove: "Earth Power" }
];

const MOVE_DATA = {
  "Vine Whip": { type: "Grass", power: 12, energy: 8 },
  "Razor Leaf": { type: "Grass", power: 15, energy: 7 },
  "Ember": { type: "Fire", power: 10, energy: 10 },
  "Fire Fang": { type: "Fire", power: 13, energy: 8 },
  "Fire Spin": { type: "Fire", power: 14, energy: 9 },
  "Water Gun": { type: "Water", power: 10, energy: 10 },
  "Thunder Shock": { type: "Electric", power: 8, energy: 12 },
  "Volt Switch": { type: "Electric", power: 16, energy: 8 },
  "Lick": { type: "Ghost", power: 6, energy: 12 },
  "Shadow Claw": { type: "Ghost", power: 13, energy: 10 },
  "Quick Attack": { type: "Normal", power: 8, energy: 10 },
  "Dragon Breath": { type: "Dragon", power: 12, energy: 8 },
  "Dragon Tail": { type: "Dragon", power: 15, energy: 8 },
  "Psycho Cut": { type: "Psychic", power: 10, energy: 12 },
  "Smack Down": { type: "Rock", power: 16, energy: 7 },
  "Counter": { type: "Fighting", power: 14, energy: 9 },
  "Mud Shot": { type: "Ground", power: 9, energy: 12 },

  "Seed Bomb": { type: "Grass", power: 55, cost: 33 },
  "Solar Beam": { type: "Grass", power: 150, cost: 100 },
  "Frenzy Plant": { type: "Grass", power: 100, cost: 45 },
  "Flame Charge": { type: "Fire", power: 70, cost: 50 },
  "Flamethrower": { type: "Fire", power: 90, cost: 55 },
  "Blast Burn": { type: "Fire", power: 110, cost: 50 },
  "Aqua Tail": { type: "Water", power: 50, cost: 35 },
  "Hydro Pump": { type: "Water", power: 130, cost: 75 },
  "Hydro Cannon": { type: "Water", power: 90, cost: 40 },
  "Thunderbolt": { type: "Electric", power: 80, cost: 50 },
  "Wild Charge": { type: "Electric", power: 90, cost: 45 },
  "Shadow Punch": { type: "Ghost", power: 45, cost: 33 },
  "Shadow Ball": { type: "Ghost", power: 100, cost: 55 },
  "Swift": { type: "Normal", power: 60, cost: 50 },
  "Body Slam": { type: "Normal", power: 60, cost: 35 },
  "Dragon Claw": { type: "Dragon", power: 50, cost: 35 },
  "Outrage": { type: "Dragon", power: 110, cost: 60 },
  "Psystrike": { type: "Psychic", power: 90, cost: 45 },
  "Stone Edge": { type: "Rock", power: 100, cost: 55 },
  "Aura Sphere": { type: "Fighting", power: 90, cost: 50 },
  "Earth Power": { type: "Ground", power: 100, cost: 55 },
  "Overheat": { type: "Fire", power: 160, cost: 100 }
};

const TYPE_COLORS = {
  Grass: "#78C850",
  Poison: "#A040A0",
  Fire: "#F08030",
  Flying: "#A890F0",
  Water: "#6890F0",
  Electric: "#F8D030",
  Ghost: "#705898",
  Normal: "#A8A878",
  Dragon: "#7038F8",
  Psychic: "#F85888",
  Rock: "#B8A038",
  Fighting: "#C03028",
  Steel: "#B8B8D0",
  Ground: "#E0C068",
  Dark: "#705848"
};
